name: Selenium Grid tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          sudo apt-get update
          pip3 install --user poetry
          poetry install
          sudo wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/local/bin/wait-for-it.sh
          sudo chmod +x /usr/local/bin/wait-for-it.sh
      - name: Start Selenium Grid containers
        working-directory: docker/
        run: |
          docker-compose -f docker-compose.yml up -d
          hub_ip=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' selenium-hub)
          wait-for-it.sh "$hub_ip:4444" -t 0
      - name: Run tests
        run: |
          export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/Selenium-Tests-Kitsune/
          poetry run pytest -m smokeTest -n2
      - name: Stop Selenium Grid containers
        working-directory: docker/
        run: |
          docker-compose -f selenium-compose.yml down