name: Selenium Grid tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          sudo apt-get update
          pip3 install --user poetry
          poetry install
      - name: Build and run Selenium Grid containers
        uses: docker/build-push-action@v2
        with:
            context: .
            file: ./docker/docker-compose.yml
            env: |
              HUB_PORT=4444
              NODE_PORT1=442
              NODE_PORT2=443
            entrypoint: docker-compose
            args: up -d

      - name: Run tests
        run: |
          export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/Selenium-Tests-Kitsune/
          poetry run pytest -m smokeTest -n2

      - name: Stop Selenium Grid containers
        uses: docker/build-push-action@v2
        with:
            context: .
            file: ./docker-compose.yml
            entrypoint: docker-compose
            args: down