name: Selenium Grid tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          sudo apt-get update
          pip3 install --user poetry
          poetry install
      - name: Start Selenium Grid containers
        working-directory: docker/
        run: |
          docker-compose build
          docker-compose up -d
      - name: Wait for Selenium Hub to be ready
        run:
          docker-compose run --rm hub sh -c 'while ! curl -sSL http://localhost:4444/wd/hub/status | grep "\"success\":true"; do sleep 1; done;'
      - name: Start Selenium tests
        run: |
          export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/Selenium-Tests-Kitsune/
          poetry run pytest -m smokeTest -n2
      - name: Stop Selenium Grid containers
        working-directory: docker/
        run: |
          docker-compose down